[project]
name = "curso-mcp-xavix46"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xavix46", email = "xavieranatoa@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=2.22.0",
    "rich>=15.0.0",
]

[project.scripts]
curso-mcp-xavix46 = "curso_mcp_xavix46:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
